locations = {
    1: {
        1: "Prologue (First Half)",
        2: "The Mural's Legend",
        3: "Prologue (Second Half)",
        4: "Memories: The Awakening",
        5: "Get Fanfare (Decayed Master Sword)",
        6: "Opening",
        7: "Field (High Sky)",
        8: "Temple of Time",
        9: "Encounter with Rauru, Source of the Right Arm",
        10: "Sky Island",
        11: "First Time in a Location (Shrine Interior)",
        12: "Shrine of Light",
        13: "Rauru's Guidance",
        14: "Battle: Field",
        15: "Rauru's Farewell",
        16: "You Must Find Me",
        17: "Diving",
        18: "Dearly-Missed Earth",
        19: "Field (Surface/Day)",
        20: "Lookout Landing",
        21: "Reunion with Purah",
        22: "Report on Events in the Depths and the Sky",
        23: "Hyrule Castle (Surface)",
        24: "Switch On",
        25: "Launch from the Skyview Tower!",
        26: "Expanding World",
        27: "Rocky Area",
        28: "Diving (Depths)",
        29: "Descend to the Depths",
        30: "Field (Depths)",
        31: "Lightroot",
        32: "Geoglyph (Rauru)",
        33: "The Dragon's Tears: Introduction",
        34: "Memories: Where Am I?",
        35: "Skyview Tower",
        36: "Cave",
        37: "Flux Construct Battle"
    },
    2: {
        1: "Field (Extreme Cold)",
        2: "Geoglyph (Ancient Hyrule Castle)",
        3: "Memories: An Unfamiliar World",
        4: "Gloom Spawn Battle",
        5: "Highlands",
        6: "Omen of the Blood Moon",
        7: "Blood Moon",
        8: "Lucky Clover Gazette",
        9: "Rito Village (During the Phenomenon)",
        10: "Reunion with Tulin",
        11: "House",
        12: "Tulin's Bow Taken",
        13: "Incoming Attack",
        14: "Investigation to the Clouds",
        15: "Cumulonimbus Cloud",
        16: "Discovering the Source of the Blizzard",
        17: "Wind Temple: 1st Stage",
        18: "Wind Temple: 2nd Stage",
        19: "Wind Temple: 3rd Stage",
        20: "Wind Temple: 4th Stage",
        21: "Wind Temple: 5th Stage",
        22: "Colgera Appears",
        23: "Colgera Battle (First Half)",
        24: "Colgera Battle (Second Half)",
        25: "Heart Container Appears",
        26: "The Ancient Rito Sage's Story",
        27: "Our Duty Was Clear",
        28: "The Destiny of Our People",
        29: "Tulin, Sage of Wind",
        30: "The Phenomenon Disappears",
        31: "Rito Village (Day)",
        32: "Rito Village (Night)",
        33: "Flight Range",
        34: "Mini-Game (Bird-Man Flight Research)",
        35: "The Arrogant Master Kohga",
        36: "Gleeok Battle"
    },
    3: {
        1: "Lava Area",
        2: "Geoglyph (Purah Pad)",
        3: "Memories: Mineru's Counsel",
        4: "Plains",
        5: "Goron City (During the Phenomenon)",
        6: "Reunion with Yunobo",
        7: "Where the Goron Tribe Is",
        8: "Field (Scorching Heat)",
        9: "YunoboCo HQ",
        10: "Marbled Rock Roast... Makes Everyone Happy...",
        11: "Yunobo (Clearly Not Himself) Battle",
        12: "Yunobo Regains His Senses",
        13: "Follow Zelda to Death Mountain",
        14: "Moragia Appears",
        15: "Moragia Battle",
        16: "Fire Temple: 1st Stage",
        17: "Fire Temple: 2nd Stage",
        18: "Fire Temple: 3rd Stage",
        19: "Fire Temple: 4th Stage",
        20: "Fire Temple: 5th Stage",
        21: "Marbled Gohma Appears",
        22: "Marbled Gohma Battle (First Half)",
        23: "Marbled Gohma Battle (Second Half)",
        24: "The Ancient Goron Sage's Story",
        25: "Yunobo, Sage of Fire",
        26: "Goron City (Day)",
        27: "Goron City (Night)",
        28: "Mini-Game (Mine-Cart Land)",
        29: "Battle: Field (Joint Fight with Monster-Control Crew)",
        30: "May the Goddess Hylia Protect You!",
        31: "Hinox Battle",
        32: "Field (Surface/Night)",
        33: "Mini-Game (Ball Toss)",
        34: "Battle: Field (Depths/Cave)",
        35: "Depths Abandoned Mine",
        36: "Furious Master Kohga",
        37: "Frox Battle"
    },
    4: {
        1: "Riding (Day)",
        2: "Waterfront",
        3: "Shrine of Light: Blessing",
        4: "Battle: Field (Boss Bokoblin)",
        5: "Zora's Domain (During the Phenomenon)",
        6: "Purify the Sludge-Covered Statue",
        7: "Encounter with Yona",
        8: "Mipha Court",
        9: "Reunion with Sidon",
        10: "Pristine Sanctum",
        11: "Sludge Like Battle",
        12: "Yona's Sentiments",
        13: "Sidon's Determination",
        14: "Into the Great Whirlpool",
        15: "Ancient Zora Waterworks",
        16: "The Zora Temple in the Sky Appears",
        17: "Field (Low Gravity)",
        18: "Water Temple: 1st Stage",
        19: "Water Temple: 2nd Stage",
        20: "Water Temple: 3rd Stage",
        21: "Water Temple: 4th Stage",
        22: "Mucktorok Appears",
        23: "Mucktorok Battle (First Half)",
        24: "Mucktorok Battle (Second Half)",
        25: "The Ancient Zora Sage's Story",
        26: "Sidon, Sage of Water",
        27: "The New King and Queen of the Zora",
        28: "Zora's Domain (Day)",
        29: "Zora's Domain (Night)",
        30: "Mini-Game (Dive Ceremony)",
        31: "Shrine of Light: Before the Trial",
        32: "Shrine of Light: Battle",
        33: "Geoglyph (Molduga)",
        34: "Memories: The Gerudo Assault",
        35: "Master Kohga Speaks",
        36: "The Return of Master Kohga: Battle",
    },
    5: {
       1: "Wasteland",
       2: "Geoglyph (Ganondorf)",
       3: "Memories: A Show of Fealty",
       4: "Field (Intense Heat)",
       5: "Gerudo Town (During the Phenomenon)",
       6: "Gerudo Shelter",
       7: "Desert Ruins",
       8: "Reunion with Riju",
       9: "Kara Kara Bazaar Defense Battle",
       10: "After the Battle at Kara Kara Bazaar",
       11: "Kara Kara Bazaar",
       12: "Gerudo Town Defense Battle",
       13: "Successful Defense of Gerudo Town",
       14: "Visions in the Desert",
       15: "The Gerudo Great Pyramid Appears",
       16: "Queen Gibdo Introduction",
       17: "Queen Gibdo Battle (First Encounter)",
       18: "Battle: Temple",
       19: "Lightning Temple: 1st Stage",
       20: "Lightning Temple: 2nd Stage",
       21: "Lightning Temple: 3rd Stage",
       22: "Lightning Temple: 4th Stage",
       23: "Queen Gibdo Appears",
       24: "Queen Gibdo Battle (First Half)",
       25: "Queen Gibdo Battle (Second Half)",
       26: "The Ancient Gerudo Sage's Story",
       27: "Riju, Sage of Lightning",
       28: "Gerudo Town (Day)",
       29: "Gerudo Town (Night)",
       30: "Noble Pursuit",
       31: "Molduga Battle",
       32: "Geoglyph (Sonia)",
       33: "Memories: Zelda and Sonia"
    },
    6: {
       1: "Geoglyph (Gerudo Scimitar)",
       2: "Memories: Sonia Is Caught by Treachery",
       3: "Signs of Monsters",
       4: "Lurelin Village Restoration Feast",
       5: "Bolson's Dance of Joy",
       6: "Lurelin Village (Day)",
       7: "Lurelin Village (Night)",
       8: "Memories: Birth of the Demon King",
       9: "The Blood Moon Rises Over Hyrule Castle",
       10: "Lookout Landing Shrouded in Dark Clouds",
       11: "",
       12: "",
       13: "",
       14: "",
       15: "",
       16: "",
       17: "",
       18: "",
       19: "",
       20: "",
       21: "",
       22: "",
       23: "",
       24: "",
       25: "",
       26: "",
       27: "",
       28: "",
       29: "",
       30: "",
       31: "",
       32: "",
       33: "",
       34: ""
    },
    7: {
       1: "",
       2: "",
       3: "",
       4: "",
       5: "",
       6: "",
       7: "",
       8: "",
       9: "",
       10: "",
       11: "",
       12: "",
       13: "",
       14: "",
       15: "",
       16: "",
       17: "",
       18: "",
       19: "",
       20: "",
       21: "",
       22: "",
       23: "",
       24: "",
       25: "",
       26: "",
       27: "",
       28: "",
       29: "",
       30: "",
       31: "",
       32: "",
       33: "",
       34: "",
       35: ""
    },
    8: {
       1: "",
       2: "",
       3: "",
       4: "",
       5: "",
       6: "",
       7: "",
       8: "",
       9: "",
       10: "",
       11: "",
       12: "",
       13: "",
       14: "",
       15: "",
       16: "",
       17: "",
       18: "",
       19: "",
       20: "",
       21: "",
       22: "",
       23: "",
       24: "",
       25: "",
       26: "",
       27: "",
       28: "",
       29: ""
    },
    9: {       
       1: "",
       2: "",
       3: "",
       4: "",
       5: "",
       6: "",
       7: "",
       8: "",
       9: "",
       10: "",
       11: "",
       12: "",
       13: "",
       14: "",
       15: "",
       16: "",
       17: "",
       18: "",
       19: "",
       20: "",
       21: "",
       22: "",
       23: "",
       24: "",
       25: "",
       26: "",
       27: "",
       28: "",
       29: "",
       30: "",
       31: "",
       32: "",
       33: "",
       34: "",
       35: "",
       36: "",
       37: "",
       38: "",
       39: "",
       40: "",
       41: "",
       42: "",
       43: "",
       44: "",
       45: "",
       46: "",
       47: "",
       48: "",
       49: "",
       50: "",
       51: "",
       52: "",
       53: "",
       54: "",
       55: "",
       56: "",
       57: "",
       58: "",
       59: "",
       60: "",
       61: "",
       62: "",
       63: "",
       64: "",
       65: "",
       66: "",
       67: ""
       },
    10: {
       1: "",
       2: "",
       3: "",
       4: "",
       5: "",
       6: "",
       7: "",
       8: "",
       9: "",
       10: "",
       11: "",
       12: "",
       13: "",
       14: "",
       15: ""
       }
}